name: Build and upload artifacts

on: [push, pull_request]

env:
  PD_MAJOR: 0
  PD_MINOR: 56
  PD_BUGFIX: 1
  PDINCLUDEDIR: ./pure-data/src
  PDLIBDIR: ./build
  LIBNAME: witsensor

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
        floatsize: [32, 64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config libbluetooth-dev libdbus-1-dev

      - name: Clone Pd
        run: git clone --branch=${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}} --depth=1 https://github.com/pure-data/pure-data.git

      - name: Build (make deps && make install)
        run: |
          make deps
          make install PDLIBDIR=${{ env.PDLIBDIR }} floatsize=${{ matrix.floatsize }} extension=${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.floatsize }}.so

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.LIBNAME}}-${{ matrix.os }}-${{ matrix.arch }}-pd${{ matrix.floatsize }}
          path: build/${{env.LIBNAME}}

  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [darwin]
        arch: [amd64, arm64]
        floatsize: [32, 64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Clone Pd
        run: git clone --branch=${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}} --depth=1 https://github.com/pure-data/pure-data.git

      - name: Build (make deps && make install)
        run: |
          ARCH=${{ matrix.arch == 'amd64' && 'x86_64' || matrix.arch }}
          make deps arch=${ARCH}
          make install PDLIBDIR=${{ env.PDLIBDIR }} floatsize=${{ matrix.floatsize }} extension=darwin-${{ matrix.arch }}-${{ matrix.floatsize }}.so arch=${ARCH}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.LIBNAME}}-${{ matrix.os }}-${{ matrix.arch }}-pd${{ matrix.floatsize }}
          path: build/${{env.LIBNAME}}

  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows]
        arch: [amd64]
        floatsize: [32, 64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v2
      
      - name: Add MSVC to PATH
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Download Pure-Data Binaries (32-bit floats)
        if: matrix.floatsize == 32
        shell: pwsh
        run: |
          Write-Host "Downloading Pd binaries for 32-bit float support..."
          Invoke-WebRequest -Uri "http://msp.ucsd.edu/Software/pd-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}.msw.zip" -OutFile "pd-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}.msw.zip"
          Expand-Archive -Path "pd-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}.msw.zip" -DestinationPath .
          
          # Debug: Check what we extracted
          Write-Host "Contents after extraction:"
          Get-ChildItem -Directory | Format-Table Name
      
      - name: Download Pure-Data Binaries (64-bit floats)
        if: matrix.floatsize == 64
        shell: pwsh
        run: |
          Write-Host "Downloading Pd64 binaries for 64-bit float support..."
          Invoke-WebRequest -Uri "https://puredata.info/downloads/pure-data/releases/${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}-pd64/Pd64-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}.msw.zip" -OutFile "pd64-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}.msw.zip"
          Expand-Archive -Path "pd64-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}.msw.zip" -DestinationPath .
          
          # Debug: Check what we extracted
          Write-Host "Contents after extraction:"
          Get-ChildItem -Directory | Format-Table Name
          
          # Rename Pd-0.* to pd-* for consistency
          Get-ChildItem -Directory -Filter 'Pd-0.*' | ForEach-Object {
            Write-Host "Renaming $($_.Name) to pd-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}"
            Rename-Item $_.FullName "pd-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}"
          }
          
          # Debug: Check final directory structure
          Write-Host "Final directory structure:"
          Get-ChildItem -Directory | Format-Table Name
      
      - name: Build SimpleBLE
        shell: pwsh
        run: |
          # Clean any previous build artifacts
          if (Test-Path SimpleBLE/simplecble/build-windows) {
            Remove-Item -Recurse -Force SimpleBLE/simplecble/build-windows
          }
          
          cd SimpleBLE/simplecble
          
          # Configure with Visual Studio generator (outputs generator info)
          cmake -S . -B build-windows -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=OFF
          
          # Build with MSBuild
          cmake --build build-windows --config Release --verbose
      
      - name: Build Pure Data external
        shell: pwsh
        run: |
          $pdDir = "pd-${{env.PD_MAJOR}}.${{env.PD_MINOR}}-${{env.PD_BUGFIX}}"
          $extension = "${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.floatsize }}.dll"
          
          # Create output directory with Windows path separators
          $outDir = "${{ env.PDLIBDIR }}\witsensor".Replace('/', '\')
          New-Item -ItemType Directory -Force -Path $outDir | Out-Null
          
          $outFile = "${outDir}\witsensor.${extension}"
          Write-Host "Output file: $outFile"
          
          # Set compiler flags - only use PDINSTANCE for 64-bit builds
          $pdFlags = if (${{ matrix.floatsize }} -eq 64) { "/DPD /DPDINSTANCE /DPD_FLOATSIZE=64" } else { "/DPD /DPD_FLOATSIZE=32" }
          
          # Determine Pd library name (pd.lib for 32-bit, may need pd64.lib for 64-bit)
          $pdLib = if (${{ matrix.floatsize }} -eq 64) { "pd64.lib" } else { "pd.lib" }
          
          # Debug: Show compiler flags
          Write-Host "Compiler flags: $pdFlags"
          Write-Host "Pd library: $pdLib"
          Write-Host "Float size: ${{ matrix.floatsize }}"
          
          # Debug: Check SimpleBLE build directory
          Write-Host "Checking SimpleBLE build directory..."
          Write-Host "Contents of SimpleBLE/simplecble/build-windows/lib/Release/:"
          Get-ChildItem "SimpleBLE/simplecble/build-windows/lib/Release/" -ErrorAction SilentlyContinue | Format-Table Name
          
          # Debug: Check Pd directory structure
          Write-Host "Checking Pd directory structure..."
          Write-Host "Contents of ${pdDir}/bin/:"
          Get-ChildItem "${pdDir}/bin/" -ErrorAction SilentlyContinue | Format-Table Name
          Write-Host "Contents of ${pdDir}/src/:"
          Get-ChildItem "${pdDir}/src/" -ErrorAction SilentlyContinue | Format-Table Name
          
          # Debug: Check if m_pd.h contains float size definitions
          Write-Host "Checking m_pd.h for float size definitions..."
          if (Test-Path "${pdDir}/src/m_pd.h") {
            $mpdContent = Get-Content "${pdDir}/src/m_pd.h" -Raw
            if ($mpdContent -match "PD_FLOATSIZE") {
              Write-Host "Found PD_FLOATSIZE in m_pd.h"
              $mpdContent | Select-String "PD_FLOATSIZE" | ForEach-Object { Write-Host "  $_" }
            } else {
              Write-Host "No PD_FLOATSIZE found in m_pd.h"
            }
            if ($mpdContent -match "t_float") {
              Write-Host "Found t_float definition in m_pd.h"
              $mpdContent | Select-String "typedef.*t_float" | ForEach-Object { Write-Host "  $_" }
            }
            # Check for double precision definitions
            if ($mpdContent -match "double") {
              Write-Host "Found 'double' in m_pd.h:"
              $mpdContent | Select-String "double" | Select-Object -First 5 | ForEach-Object { Write-Host "  $_" }
            }
          }
          
          # Check if we need to link against static libraries instead
          if (Test-Path "SimpleBLE/simplecble/build-windows/lib/Release/simpleble.lib") {
            Write-Host "Found simpleble.lib - this is a static library"
          }
          if (Test-Path "SimpleBLE/simplecble/build-windows/lib/Release/simplecble.lib") {
            Write-Host "Found simplecble.lib - this is also needed"
          }
          
          # Debug: Test compilation with a simple float size check
          Write-Host "Testing float size compilation..."
          $testCode = "#include <stdio.h>`n#include `"${pdDir}/src/m_pd.h`"`nint main() {`n    printf(`"sizeof(t_float) = %d\n`", sizeof(t_float));`n    printf(`"PD_FLOATSIZE = %d\n`", PD_FLOATSIZE);`n    return 0;`n}"
          $testCode | Out-File -FilePath "test_floatsize.c" -Encoding ASCII
          
          # Compile source files with MSVC
          cl /nologo $pdFlags `
            /I. /I"SimpleBLE/simplecble/include" /I"SimpleBLE/simpleble/include" `
            /I"SimpleBLE/simplecble/build-windows/simpleble/export" `
            /I"${pdDir}/src" `
            /O2 /W3 /LD /MD `
            pd-witsensor-ble.c witsensor_ble_simpleble.c `
            /link /DLL "/OUT:${outFile}" `
            "/LIBPATH:${pdDir}/bin" $pdLib `
            "SimpleBLE/simplecble/build-windows/lib/Release/simpleble.lib" `
            "SimpleBLE/simplecble/build-windows/lib/Release/simplecble.lib" `
            ws2_32.lib iphlpapi.lib ole32.lib setupapi.lib windowsapp.lib `
            legacy_stdio_definitions.lib ucrt.lib vcruntime.lib msvcrt.lib

          # Copy help files
          Copy-Item "witsensor-help.pd" "$outDir\"
          Copy-Item "README.md" "$outDir\"
          
          # Debug: Inspect the created DLL
          Write-Host "Inspecting created DLL: $outFile"
          if (Test-Path $outFile) {
            Write-Host "DLL exists and is $((Get-Item $outFile).Length) bytes"
            # Try to get DLL info using dumpbin if available
            try {
              $dumpbinOutput = & dumpbin /exports $outFile 2>$null
              if ($dumpbinOutput) {
                Write-Host "DLL exports:"
                $dumpbinOutput | Select-String "witsensor" | ForEach-Object { Write-Host "  $_" }
              }
            } catch {
              Write-Host "dumpbin not available for DLL inspection"
            }
          } else {
            Write-Host "ERROR: DLL was not created!"
          }
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.LIBNAME}}-${{ matrix.os }}-${{ matrix.arch }}-pd${{ matrix.floatsize }}
          path: build/${{env.LIBNAME}}

  package_and_release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_macos, build_windows]
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge Artifacts to Package
        run: |
          mkdir -p ${{env.LIBNAME}}
          cp -rn artifacts/${{env.LIBNAME}}-*/* ${{env.LIBNAME}}

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.LIBNAME}}-package
          path: ${{env.LIBNAME}}

  deken_check_and_upload:
    runs-on: ubuntu-latest
    needs: [package_and_release]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{env.LIBNAME}}-src

      - uses: actions/download-artifact@v4
        with:
          name: ${{env.LIBNAME}}-package
          path: ${{env.LIBNAME}}

      - name: Check Deken Package
        shell: bash
        run: |
          SHORT=${GITHUB_REF:11}
          SLUG=${SHORT//\//_}
          echo "## package" | tee -a $GITHUB_STEP_SUMMARY
          mkdir -p package
          docker run --rm --user $(id -u) --volume ./witsensor:/witsensor --volume ./package:/package registry.git.iem.at/pd/deken \
            deken package --output-dir /package --version "${SLUG}" /witsensor

          dek_files=$(ls package/*.dek)
          for dek_file in $dek_files; do
            filename=$(basename "$dek_file")
            echo -e "#### \`$filename\`" | tee -a $GITHUB_STEP_SUMMARY
            echo '```' | tee -a $GITHUB_STEP_SUMMARY
            unzip -l "$dek_file" | awk 'NR>3 {print $4}' | sed '/^$/d' | sort | tee -a $GITHUB_STEP_SUMMARY
            echo '```' | tee -a $GITHUB_STEP_SUMMARY
          done

      - name: Upload Deken Package
        if: ${{ !contains(github.ref, 'test') }}
        shell: bash
        env:
          DEKEN_USERNAME: ${{ secrets.DEKEN_USERNAME }}
          DEKEN_PASSWORD: ${{ secrets.DEKEN_PASSWORD }}
        run: |
          SHORT=${GITHUB_REF:11}
          SLUG=${SHORT//\//_}
          # Upload platform-specific package
          docker run --rm -e DEKEN_USERNAME -e DEKEN_PASSWORD \
            --volume ./witsensor:/witsensor registry.git.iem.at/pd/deken \
            deken upload --name ${{env.LIBNAME}} --version "${SLUG}" --no-source-error /witsensor
          # Upload source code
          docker run --rm -e DEKEN_USERNAME -e DEKEN_PASSWORD \
            --volume ./witsensor-src:/witsensor registry.git.iem.at/pd/deken \
            deken upload --name ${{env.LIBNAME}} --version "${SLUG}" /witsensor
